package com.udacity.cscan.daoimage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMAGE".
 */
public class Image {
    private Long id;
    /**
     * Not-null value.
     */
    private String title;
    private String comment;
    /**
     * Not-null value.
     */
    private String imageurl;
    private java.util.Date date;
    private String formateddate;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String title, String comment, String imageurl, java.util.Date date, String formateddate) {
        this.id = id;
        this.title = title;
        this.comment = comment;
        this.imageurl = imageurl;
        this.date = date;
        this.formateddate = formateddate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Not-null value.
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getFormateddate() {
        return formateddate;
    }

    public void setFormateddate(String formateddate) {
        this.formateddate = formateddate;
    }

}
